work_dir: ./work_dir/ntu120/xset/lst_bone_vel

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu120/NTU120_CSet.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: True
  bone: False

test_feeder_args:
  data_path: data/ntu120/NTU120_CSet.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: True
  bone: False
  debug: False

# model
model: model.ctrgcn.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  k: 1
  head: ['ViT-B/32']
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0005
base_lr: 0.1
lr_decay_rate: 0.1
step: [90, 100]
warm_up_epoch: 5

# training
device: [0]
batch_size: 200
test_batch_size: 200
num_epoch: 110
nesterov: True
